# This is a basic workflow to help you get started with Actions

name: Azure Key Vault Secret Creds

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set  environment 
        run: |
          sudo apt-get update -y
          sudo apt-get install azure-cli jq gh -y
                    
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      
      - name: Get secret from Azure Key Vault
        run: |
          
            secretValue=$(az keyvault secret show --name "newtest" --vault-name "kvmariotest" --query "value")
            echo "SECRETVALUE="$secretValue
        env:
          AZURE_KEYVAULT_URI: ${{ secrets.AZURE_KEYVAULT_URI }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
